### PR TITLE
✨feat: add option to hide shorts everywhere

### PR DESCRIPTION
**Pull request by 0xatulpatil**
Added feature to hide shorts everywhere.

### CODE REVIEW

**Comment by remi-garcia** [comment]
Closes #57

**Comment by lawrencehook** [comment]
It's a good start! I'm going to merge, and make some changes

**Comment by 0xatulpatil** [comment]
Hey, could you please describe what all changes you made to the codebase?
Would definitely help me.

**Comment by lawrencehook** [comment]
Here's the commit 0c6cec355a84d9dcd6ed60d16e6898fb0922cc0b

Do you have any particular questions?

**Pull request merged**
